### ISSUE TITLE
Dedicated server crashing on loading Map Atlases

### ISSUE THREAD

**Issue by dylansmrjones** [Pepperoni-Jabroni/MapAtlasesForge#1]
[crash-2021-03-07_19.10.23-fml.txt](https://github.com/Pepperoni-Jabroni/MapAtlasesForge/files/6097746/crash-2021-03-07_19.10.23-fml.txt)

I know I know. The mod isn't released yet, using it will take a life from a kitten in your favorite minecraft world etc. But we might as well start the bug hunting ;)

The forge server fails to load with following exception

 java.lang.RuntimeException: Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER
 
I hope the mod is ultimately meant for multiplayer servers, for this mod is exactly what I've been looking for.

**Comment by Pepperoni-Jabroni** [comment]
This is in very, very early stages of development for Forge right now. I don't actually think I'll take this route for implementation - I'll probably use Architectury API. In any case, I'm going to close this out since it's not meant to be compiled or ran in any form right now. Thanks for the detailed report though!
