### ISSUE TITLE
awful performance on SMP

### ISSUE THREAD

**Issue by k1r0s** [Pepperoni-Jabroni/MapAtlasesForge#2]
hey, congrats for the nice work

This is a common bug in map mods, or I guess related to the way vanilla maps works: https://github.com/svenhjol/CharmForge/issues/137

I dunno if this is helpful for you, maybe it cannot be avoided

https://spark.lucko.me/7bHZKwKNls

![imagen](https://user-images.githubusercontent.com/6052309/146281841-571fca5f-2ab4-49ef-9689-1479c00cd285.png)

Xaero's minimap or journey map do not use the server at all, which is good for performance but I really like the vanilla map, the interaction it provides as can be shared with friends, etc, used in wall frames. I find this mod interesting (all mods that improve vanilla maps)

Ping me if you need anything for me! GL

**Comment by Pepperoni-Jabroni** [comment]
Thank you for the report @k1r0s! Is this about the Forge version of Map Atlases (e.g. the one published here: https://www.curseforge.com/minecraft/mc-mods/map-atlases-forge)? If so, then that's actually an independent mod from the one on this repository (which is completely unfinished and broken). Please also report this to u/caltinor in his Curseforge page's comments section, since it doesn't look like he's published a GH for Issues.

This reminds me that I should probably delete this repo to avoid confusion. My implementation of Map Atlases for Forge never made it very far.

I'd also be curious to know if the Fabric version of Map Atlases has the same performance issue. My guess would be absolutely yes, but it'd be nice to confirm.

I'll also close out this Issue since this isn't a supported/functioning version of this mod. Anyway, thanks again for reporting!

**Comment by k1r0s** [comment]
Oh, I noticed that your mod curseforge page didn't have a source link. I though you missed that but I was wrong.

Regarding the map vanilla performance, do you know if this is something related to minecraft it self or specifically with forge build. Maybe I'll try fabric at some point. Looks like its a better place to put the money
